In [322]:
# pip install giotto-tda
# pip install gudhi

In [323]:
import pandas as pd
import numpy as np
import matplotlib as plt
from gtda.time_series import SingleTakensEmbedding, TakensEmbedding

series = np.log(pd.read_csv("SP500.csv", header=None).to_numpy().squeeze())

print(series)


[7.13389833 7.14663437 7.15787955 7.15000317 7.15460754 7.17081353
 7.1664011  7.15850232 7.15946102 7.16732333 7.16110014 7.14610857
 7.14739207 7.14883305 7.15964177 7.15205153 7.14628387 7.15252724
 7.16494271 7.16181205 7.16068091 7.14995608 7.1324017  7.11748932
 7.14356823 7.1275111  7.11751162 7.11588874 7.12676429 7.1003324
 7.083176   7.07167947 7.07524869 7.13058478 7.11353698 7.09150706
 7.07971711 7.09110755 7.09088068 7.04975602 7.04385182 7.05262589
 7.033771   7.02098128 6.96319235 6.94063381 6.89343574 6.86238651
 6.78607058 6.87410801 6.92364831 6.85162134 6.82220011 6.84764428
 6.87451644 6.87316383 6.81779775 6.80058479 6.7681397  6.75974239
 6.80223086 6.84576817 6.8574904  6.86967691 6.8744389  6.90109565
 6.8813343  6.82972617 6.82546547 6.83743206 6.80419869 6.76743518
 6.77423817 6.78875494 6.75812644 6.74558041 6.7259366  6.65814903
 6.65470005 6.72647918 6.75396287 6.76198067 6.79041496]


In [324]:
# initial values for important variables -- will have to find optimal values later on

n = 4 # dim of vectors
d = 5 # time delay
w = 5 # window size
epsilon = 0.1 # resolution threshold
q = 3 # number of precision qubits

In [325]:
STE = SingleTakensEmbedding(time_delay = d, dimension = n)
STE.fit_transform(series)

array([[7.13389833, 7.15000317, 7.1664011 ],
       [7.14663437, 7.15460754, 7.15850232],
       [7.15787955, 7.17081353, 7.15946102],
       [7.15000317, 7.1664011 , 7.16732333],
       [7.15460754, 7.15850232, 7.16110014],
       [7.17081353, 7.15946102, 7.14610857],
       [7.1664011 , 7.16732333, 7.14739207],
       [7.15850232, 7.16110014, 7.14883305],
       [7.15946102, 7.14610857, 7.15964177],
       [7.16732333, 7.14739207, 7.15205153],
       [7.16110014, 7.14883305, 7.14628387],
       [7.14610857, 7.15964177, 7.15252724],
       [7.14739207, 7.15205153, 7.16494271],
       [7.14883305, 7.14628387, 7.16181205],
       [7.15964177, 7.15252724, 7.16068091],
       [7.15205153, 7.16494271, 7.14995608],
       [7.14628387, 7.16181205, 7.1324017 ],
       [7.15252724, 7.16068091, 7.11748932],
       [7.16494271, 7.14995608, 7.14356823],
       [7.16181205, 7.1324017 , 7.1275111 ],
       [7.16068091, 7.11748932, 7.11751162],
       [7.14995608, 7.14356823, 7.11588874],
       [7.

In [326]:
def TakenEmbedding(time_series, dim, delay):
    STE = SingleTakensEmbedding(time_delay = delay, dimension = dim)
    return STE.fit_transform(series)

In [327]:
def TakenPointCloud(embedding, window_size):
    point_cloud = []
    l = len(embedding)
    for i in range(l - window_size):
        window = embedding[i : i + window_size]
        point_cloud.append(window)

    return np.array(point_cloud)

Following Takens' embedding theorem, transform the `time_series` into a series of $ N $-dimensional vectors. Afterward, apply a sliding window to these vectors and obtain a time-varying point cloud.

In [328]:
embedding = TakenEmbedding(series, n, d)

In [329]:
point_cloud = TakenPointCloud(embedding, w)
# a Python list of numpy vectors of numpy vectors containing all the different point clouds. 
print(point_cloud)

[[[7.13389833 7.15000317 7.1664011 ]
  [7.14663437 7.15460754 7.15850232]
  [7.15787955 7.17081353 7.15946102]
  [7.15000317 7.1664011  7.16732333]
  [7.15460754 7.15850232 7.16110014]]

 [[7.14663437 7.15460754 7.15850232]
  [7.15787955 7.17081353 7.15946102]
  [7.15000317 7.1664011  7.16732333]
  [7.15460754 7.15850232 7.16110014]
  [7.17081353 7.15946102 7.14610857]]

 [[7.15787955 7.17081353 7.15946102]
  [7.15000317 7.1664011  7.16732333]
  [7.15460754 7.15850232 7.16110014]
  [7.17081353 7.15946102 7.14610857]
  [7.1664011  7.16732333 7.14739207]]

 ...

 [[6.83743206 6.77423817 6.74558041]
  [6.80419869 6.78875494 6.7259366 ]
  [6.76743518 6.75812644 6.65814903]
  [6.77423817 6.74558041 6.65470005]
  [6.78875494 6.7259366  6.72647918]]

 [[6.80419869 6.78875494 6.7259366 ]
  [6.76743518 6.75812644 6.65814903]
  [6.77423817 6.74558041 6.65470005]
  [6.78875494 6.7259366  6.72647918]
  [6.75812644 6.65814903 6.75396287]]

 [[6.76743518 6.75812644 6.65814903]
  [6.77423817 6.745580